"""Remove Role model and update relationships

Revision ID: 1004af9e685b
Revises: 0e67a8aaeece
Create Date: 2024-08-26 09:12:08.558419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1004af9e685b'
down_revision: Union[str, None] = '0e67a8aaeece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roles_id', table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('role_type', mysql.ENUM('VISITOR', 'USER', 'AUTHOR', 'PC_CHAIR', 'PC_MEMBER', 'ADMIN'), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('conference_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], name='roles_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='roles_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_roles_id', 'roles', ['id'], unique=False)
    # ### end Alembic commands ###
