"""Update user model to remove role column and adjust relationships

Revision ID: 41c853bdb404
Revises: f0f299c9828a
Create Date: 2024-08-27 00:23:25.649926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c853bdb404'
down_revision: Union[str, None] = 'f0f299c9828a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conference_pc_chairs_ibfk_2', 'conference_pc_chairs', type_='foreignkey')
    op.create_foreign_key(None, 'conference_pc_chairs', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'conference_pc_chairs', type_='foreignkey')
    op.create_foreign_key('conference_pc_chairs_ibfk_2', 'conference_pc_chairs', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
