"""Update Paper model for MySQL compatibility

Revision ID: 6dee26a3eea1
Revises: d7b5ddc74064
Create Date: 2024-08-30 16:38:03.499116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dee26a3eea1'
down_revision: Union[str, None] = 'd7b5ddc74064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('keywords', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'keywords')
    # ### end Alembic commands ###
