"""Update Paper and User models

Revision ID: d7b5ddc74064
Revises: d7200800a299
Create Date: 2024-08-30 12:37:57.925196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b5ddc74064'
down_revision: Union[str, None] = 'd7200800a299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('paper_authors_ibfk_1', 'paper_authors', type_='foreignkey')
    op.create_foreign_key(None, 'paper_authors', 'papers', ['paper_id'], ['id'])
    op.drop_constraint('papers_ibfk_1', 'papers', type_='foreignkey')
    op.create_foreign_key(None, 'papers', 'conferences', ['conference_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'papers', type_='foreignkey')
    op.create_foreign_key('papers_ibfk_1', 'papers', 'conferences', ['conference_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'paper_authors', type_='foreignkey')
    op.create_foreign_key('paper_authors_ibfk_1', 'paper_authors', 'papers', ['paper_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
