"""Update conference model

Revision ID: f0f299c9828a
Revises: 1004af9e685b
Create Date: 2024-08-26 17:05:09.752936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f0f299c9828a'
down_revision: Union[str, None] = '1004af9e685b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conferences', 'end_date')
    op.drop_column('conferences', 'submission_deadline')
    op.drop_column('conferences', 'location')
    op.drop_column('conferences', 'website')
    op.drop_column('conferences', 'start_date')
    op.drop_column('conferences', 'decision_deadline')
    op.drop_column('conferences', 'is_active')
    op.drop_column('conferences', 'final_submission_deadline')
    op.drop_column('conferences', 'review_deadline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conferences', sa.Column('review_deadline', mysql.DATETIME(), nullable=True))
    op.add_column('conferences', sa.Column('final_submission_deadline', mysql.DATETIME(), nullable=True))
    op.add_column('conferences', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('conferences', sa.Column('decision_deadline', mysql.DATETIME(), nullable=True))
    op.add_column('conferences', sa.Column('start_date', mysql.DATETIME(), nullable=True))
    op.add_column('conferences', sa.Column('website', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('conferences', sa.Column('location', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('conferences', sa.Column('submission_deadline', mysql.DATETIME(), nullable=True))
    op.add_column('conferences', sa.Column('end_date', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
